name: 错误报告
description: 报告一个错误以帮助我们改进VideoTogether
title: "[错误报告] "

body:
  - type: markdown
    attributes:
      value: |
        首先，非常感谢您抽出时间来填写此份错误报告
        请注意，任何遗漏了重要内容的bug报告我们将会不予理会
  - type: textarea
    id: bug-description
    attributes:
      label: |
        BUG描述
      description: |
        请告诉我们你遇到了什么问题
      placeholder: |
        包括你尝试了什么，你期望发生什么，以及实际发生了什么。细节越多越好！
    validations:
      required: true
  - type: input
    id: VideoTogether-version
    attributes:
      label: |
        VideoTogether版本
      description: |
        如果你使用的不是自己编译的版本，那么写`最新`就行了
        否则，请写编译的commit id
    validations:
      required: true
  - type: textarea
    id: system-architecture
    attributes:
      label: |
        环境
      description: |
        请填写您所使用的是哪种环境，细节越多越好！
        例子：
        视频网址，这是最重要的，很多时候不能同步是因为视频网站遇到了兼容性问题：https://m.bilibili.com/video/BV13t4y157KU
        系统：Windows 10 21H2 19044.1806
        浏览器：Chrome 103.0.5060.114（正式版本） （64 位）
        插件：Tampermonkey 4.16.1
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: |
        复现步骤
      description: |
        如果这是由于操作所产生的，我们需要复现步骤才能更好的解决您的问题
      value: |
        1.
        2.
        3.
        ...
  - type: checkboxes
    id: area
    attributes:
      label: |
        确认一遍
      options:
        - label: "我已完成且认真地填写完了报告所需要的信息"
        - label: "我确保没有重复的报告 [(搜索一下)](https://github.com/VideoTogether/VideoTogether/issues?q=is%3Aissue)"
